package br.com.upf.agendamento.view;

import br.com.parcerianet.utilcomp.components.formatacao.LimitaTextField;
import br.com.upf.agendamento.control.basico.PacienteCon;
import br.com.upf.agendamento.model.basico.Paciente;
import br.com.upf.agendamento.view.imagens.Imagens;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import org.hibernate.criterion.Restrictions;

/**
 *
 * @author Ademilsom
 */
public class CadastroPacienteRapidoForm extends javax.swing.JPanel {

    /**
     * Creates new form CadastroPacienteRapidoForm
     */
    
    private Paciente paciente;
    public CadastroPacienteRapidoForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlBotoes = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        pnlDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txfNomePaciente = new javax.swing.JTextField();
        lblFone = new javax.swing.JLabel();
        txfFone = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Rápido de Pacientes"));
        setLayout(new java.awt.BorderLayout());

        pnlBotoes.setLayout(new java.awt.GridBagLayout());

        btnCancelar.setIcon(Imagens.IMG_CANCEL);
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlBotoes.add(btnCancelar, gridBagConstraints);

        btnSalvar.setIcon(Imagens.IMG_SAVE);
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        pnlBotoes.add(btnSalvar, gridBagConstraints);

        add(pnlBotoes, java.awt.BorderLayout.SOUTH);

        pnlDados.setLayout(new java.awt.GridBagLayout());

        lblNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 0, 0);
        pnlDados.add(lblNome, gridBagConstraints);

        txfNomePaciente.setColumns(20);
        txfNomePaciente.setDocument(new LimitaTextField(30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(30, 5, 0, 0);
        pnlDados.add(txfNomePaciente, gridBagConstraints);

        lblFone.setText("Fone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 30, 0);
        pnlDados.add(lblFone, gridBagConstraints);

        txfFone.setColumns(8);
        txfFone.setDocument(new LimitaTextField(15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 30, 0);
        pnlDados.add(txfFone, gridBagConstraints);

        add(pnlDados, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblFone;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JTextField txfFone;
    private javax.swing.JTextField txfNomePaciente;
    // End of variables declaration//GEN-END:variables


    public boolean gravarPaciente(){
        if(txfNomePaciente.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "O nome é obrigatório.");
            return false;
        }
        
        PacienteCon pacienteCon = new PacienteCon();

        pacienteCon.setCriterions(new Object[]{
            new Object[]{"this", Restrictions.eq("nmPaciente", txfNomePaciente.getText())}
        });

        if (!pacienteCon.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Já existe um paciente com este nome.");
            return false;
        }

        pacienteCon.incluir();
        pacienteCon.getObjeto().setNmPaciente(txfNomePaciente.getText());
        pacienteCon.getObjeto().setFone(txfFone.getText());
        pacienteCon.gravar();
        
        paciente = pacienteCon.getObjeto();
        
        return true;
    }
    
    public void limpaField(){
        txfFone.setText("");
        txfNomePaciente.setText("");
    }
    
    public Paciente getPaciente() {
        return paciente;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnSalvar() {
        return btnSalvar;
    }
}
